name: Upper Air Temperature
title: 2.4.4 Upper Air Temperature
lead: Based on multiple independent analyses of measurements from radiosondes and satellite sensors it is virtually certain that globally the troposphere has warmed and the stratosphere has cooled since the mid-20th century.

# 2.4.4 Upper Air Temperature

AR4 summarized that globally the troposphere had warmed at a rate greater than the GMST over the radiosonde record, while over the shorter satellite era the GMST and tropospheric warming rates were indistinguishable. Trends in the tropics were more uncertain than global trends although even this region was concluded to be warming. Globally, the stratosphere was reported to be cooling over the satellite era starting in 1979. New advances since AR4 have highlighted the substantial degree of uncertainty in both satellite and balloon-borne radiosonde records and led to some revisions and improvements in existing products and the creation of a number of new data products.

## 2.4.4.1 Advances in Multi-Decadal Observational Records

The major global radiosonde records extend back to 1958, with temperatures, measured as the balloon ascends, reported at mandatory pressure levels. Satellites have monitored tropospheric and lower stratospheric temperature trends since late 1978 through the Microwave Sounding Unit (MSU) and its follow-on Advanced Microwave Sounding Unit (AMSU) since 1998. These measures of upwelling radiation represent bulk (volume averaged) atmospheric temperature (Figure 2.23). The ‘Mid-Tropospheric’ (MT) MSU channel that most directly corresponds to the troposphere has 10 to 15% of its signal from both the skin temperature of the Earth’s surface and the stratosphere. Two alternative approaches have been suggested for removing the stratospheric component based on differencing of view angles (LT) and statistical recombination (*G) with the ‘Lower Stratosphere’ (LS) channel ({'Spencer_and_Christy_1992}; {'Fu_et_al_2004}). The MSU satellite series also included a Stratospheric Sounding Unit (SSU) that measured at higher altitudes ({'Seidel_et_al_2011}).

{image-right:'Fig23}

At the time of AR4 there were only two ‘global’ radiosonde data sets that included treatment of homogeneity issues: RATPAC ({'Free_et_al_2005}) and HadAT ({'Thorne_et_al_2005}). Three additional estimates have appeared since AR4 based on novel and distinct approaches. A group at the University of Vienna have produced RAOBCORE and RICH ({'Haimberger_2007}; {'Haimberger_et_al_2008}, 2012) using ERA reanalysis products ({Box23 Box 2.3}). Sherwood and colleagues developed an iterative universal kriging approach for radiosonde data to create IUK ({'Sherwood_et_al_2008}) and concluded that non-climatic data issues leading to spurious cooling remained in the deep tropics even after homogenization. The HadAT group created an automated version, undertook systematic experimentation and concluded that the parametric uncertainty ({Box21 Box 2.1}) was of the same order of magnitude as the apparent climate signal ({'McCarthy_et_al_2008}; {'Titchner_et_al_2009}; {'Thorne_et_al_2011}). A similar ensemble approach has also been applied to the RICH product ({'Haimberger_et_al_2012}). These various ensembles and new products exhibit more tropospheric warming / less stratospheric cooling than pre-existing products at all levels. Globally the radiosonde records all imply the troposphere has warmed and the stratosphere cooled since 1958 but with uncertainty that grows with height and is much greater outside the better-sampled NH extra-tropics ({'Thorne_et_al_2011}; {'Haimberger_et_al_2012}), where it is of the order 0.1°C per decade.

For MSU, AR4 considered estimates produced from three groups: UAH (University of Alabama in Huntsville); RSS (Remote Sensing Systems) and VG2 (now no longer updated). A new product has been created by NOAA labelled STAR, using a fundamentally distinct approach for the critical inter-satellite warm target calibration step ({'Zou_et_al_2006a}). STAR exhibits more warming/less cooling at all levels than UAH and RSS. For MT and LS, {'Zou_and_Wang_2010 Zou and Wang (2010)} concluded that this does not relate primarily to use of their inter-satellite calibration technique but rather differences in other processing steps. RSS also produced a parametric uncertainty ensemble ({Box21 Box 2.1}) employing a Monte Carlo approach allowing methodological inter-dependencies to be fully expressed ({'Mears_et_al_2011}). For large-scale trends dominant effects were inter-satellite offset determinations and, for tropospheric channels, diurnal drift. Uncertainties were concluded to be of the order 0.1°C per decade at the global mean for both tropospheric channels (where it is of comparable magnitude to the long-term trends) and the stratospheric channel.

SSU provides the only long-term near-global temperature data above the lower stratosphere, with the series terminating in 2006. Some AMSU-A channels have replaced this capability and efforts to understand the effect of changed measurement properties have been undertaken ({'Kobayashi_et_al_2009}). Until recently only one SSU data set existed ({'Nash_and_Edge_1989}), updated by {'Randel_et_al_2009 Randel et al. (2009)}. {'Liu_and_Weng_2009 Liu and Weng (2009)} have produced an intermediate analysis for Channels 25 and 26 (but not Channel 27). Wang et al. (2012g), building on insights from several of these recent studies, have produced a more complete analysis. Differences between the independent estimates are much larger than differences between MSU records or radiosonde records at lower levels, with substantial inter-decadal time series behaviour departures, zonal trend structure, and global trend differences of the order 0.5°C per decade ({'Seidel_et_al_2011}; {'Thompson_et_al_2012}; Wang et al., 2012g). Although all SSU data sets agree that the stratosphere is cooling, there is therefore low confidence in the details above the lower stratosphere.

In summary, many new data sets have been produced since AR4 from radiosondes and satellites with renewed interest in satellite measurements above the lower stratosphere. Several studies have attempted to quantify the parametric uncertainty ({Box21 Box 2.1}) more rigorously. These various data sets and analyses have served to highlight the degree of uncertainty in the data and derived products.

## 2.4.4.2 Intercomparisons of Various Long-Term Radiosonde and MSU Products

Since AR4 there have been a large number of intercomparisons between radiosonde and MSU data sets. Interpretation is complicated, as most studies considered data set versions that have since been superseded. Several studies compared UAH and RSS products to local, regional or global raw/homogenized radiosonde data ({'Christy_and_Norris_2006}, 2009; {'Christy_et_al_2007}, 2010, 2011; {'Randall_and_Herman_2008}; {'Mears_et_al_2012}; Po-Chedley and Fu, 2012). Early studies focussed on the time of transition from NOAA-11 to NOAA-12 (early 1990s) which indicated an apparent issue in RSS. {'Christy_et_al_2007 Christy et al. (2007)} noted that this coincided with the Mt Pinatubo eruption and that RSS was the only product, either surface or tropospheric, that exhibited tropical warming immediately after the eruption when cooling would be expected. Using reanalysis data {'Bengtsson_and_Hodges_2011 Bengtsson and Hodges (2011)} also found evidence of a potential jump in RSS in 1993 over the tropical oceans. {'Mears_et_al_2012 Mears et al. (2012)} cautioned that an El Niño event quasi-simultaneous with Pinatubo complicates interpretation. They also highlighted several other periods of disagreement between radiosonde records and MSU records. All MSU records were most uncertain when satellite orbits are drifting rapidly ({'Christy_and_Norris_2006}, 2009). {'Mears_et_al_2011 Mears et al. (2011)} found that trend differences between RSS and other data sets could not be explained in many cases by parametric uncertainties in RSS alone. It was repeatedly cautioned that there were potential common biases (of varying magnitude) between the different MSU records or between the different radiosonde records which complicate intercomparisons ({'Christy_and_Norris_2006}, 2009; {'Mears_et_al_2012}).

In summary, assessment of the large body of studies comparing various long-term radiosonde and MSU products since AR4 is hampered by data set version changes, and inherent data uncertainties. These factors substantially limit the ability to draw robust and consistent inferences from such studies about the true long-term trends or the value of different data products.

## 2.4.4.3 Additional Evidence from Other Technologies and Approaches

Global Positioning System (GPS) radio occultation (RO) currently represents the only self-calibrated SI traceable raw satellite measurements ({'Anthes_et_al_2008}; {'Anthes_2011}). The fundamental observation is time delay of the occulted signal’s phase traversing the atmosphere. The time delay is a function of several atmospheric physical state variables. Subsequent analysis converts the time delay to temperature and other parameters, which inevitably adds some degree of uncertainty to the derived temperature data. Intercomparisons of GPS-RO products show that differences are largest for derived geophysical parameters (including temperature), but are still small relative to other observing technologies ({'Ho_et_al_2012}). Comparisons to MSU and radiosondes ({'Kuo_et_al_2005}; {'Ho_et_al_2007}, 2009a, 2009b; {'He_et_al_2009}; {'Baringer_et_al_2010}; {'Sun_et_al_2010}; {'Ladstadter_et_al_2011}) show substantive agreement in interannual behaviour, but also some multi-year drifts that require further examination before this additional data source can usefully arbitrate between different MSU and radiosonde trend estimates.

Atmospheric winds are driven by thermal gradients. Radiosonde winds are far less affected by time-varying biases than their temperatures ({'Gruber_and_Haimberger_2008}; {'Sherwood_et_al_2008}; Section 2.7.3). {'Allen_and_Sherwood_2007 Allen and Sherwood (2007)} initially used radiosonde wind to infer temperatures within the Tropical West Pacific warm pool region, then extended this to a global analysis ({'Allen_and_Sherwood_2008}) yielding a distinct tropical upper tropospheric warming trend maximum within the vertical pro le, but with large uncertainty. Winds can only quantify relative changes and require an initialization (location and trend at that location) ({'Allen_and_Sherwood_2008}). The large uncertainty range was predominantly driven by this initialization choice, a finding later confirmed by {'Christy_et_al_2010 Christy et al. (2010)}, who in addition questioned the stability given the sparse geographical sampling, particularly in the tropics, and possible systematic sampling effects amongst other potential issues. Initializing closer to the tropics tended to reduce or remove the appearance of a tropical upper tropospheric warming trend maximum ({'Allen_and_Sherwood_2008}; {'Christy_et_al_2010}). There is only low confidence in trends inferred from ‘thermal winds’ given the relative immaturity of the analyses and their large uncertainties.

In summary, new technologies and approaches have emerged since AR4. However, these new technologies and approaches either constitute too short a record or are too immature to inform assessments of long-term trends at the present time.

## 2.4.4.4 Synthesis of Free Atmosphere Temperature Estimates

Global-mean lower tropospheric temperatures have increased since the mid-20th century (Figure 2.24, bottom). Structural uncertainties ({Box21 Box 2.1}) are larger than at the surface but it can still be concluded that globally the troposphere has warmed (Table 2.8). On top of this long-term trend are superimposed short-term variations that are highly correlated with those at the surface but of somewhat greater amplitude. Global mean lower stratospheric temperatures have decreased since the mid20th century punctuated by short-lived warming events associated with explosive volcanic activity (Figure 2.24a). However, since the mid-1990s little net change has occurred. Cooling rates are on average greater from radiosonde data sets than MSU data sets. This very likely relates to widely recognized cooling biases in radiosondes ({'Mears_et_al_2006}) which all data set producers explicitly caution are likely to remain to some extent in their  nal products ({'Free_and_Seidel_2007}; {'Haimberger_et_al_2008}; {'Sherwood_et_al_2008}; {'Thorne_et_al_2011}).

{image:'Fig24}

In comparison to the surface (Figure 2.22), tropospheric layers exhibit smoother geographic trends (Figure 2.25) with warming dominating cooling north of approximately 45°S and greatest warming in high northern latitudes. The lower stratosphere cooled almost everywhere but this cooling exhibits substantial large-scale structure. Cooling is greatest in the highest southern latitudes and smallest in high northern latitudes. There are also secondary stratospheric cooling maxima in the mid-latitude regions of each hemisphere.

{image:'Fig25}

Available global and regional trends from radiosondes since 1958 (Figure 2.26) show agreement that the troposphere has warmed and the stratosphere cooled. While there is little ambiguity in the sign of the changes, the rate and vertical structure of change are distinctly data set dependent, particularly in the stratosphere. Differences are greatest in the tropics and SH extra-tropics where the historical radiosonde data coverage is poorest. Not shown in the  gure for clarity are estimates of parametric data set uncertainties or trendt uncertainties—both of which are of the order of at least 0.1°C per decade (Section 2.4.4.1).

{image:'Fig26}

Differences in trends between available radiosonde data sets are greater during the satellite era than for the full radiosonde period of record in all regions and at most levels (Figure 2.27; cf. Figure 2.26). The RAOBCORE product exhibits greater vertical trend gradients than other data sets and it has been posited that this relates to its dependency on reanalysis fields ({'Sakamoto_and_Christy_2009}; {'Christy_et_al_2010}). MSU trend estimates in the troposphere are generally bracketed by the radiosonde range. In the stratosphere MSU deep layer estimates tend to show slightly less cooling. Over both 1958–2011 and 1979–2011 there is some evidence in the radiosonde products taken as a whole that the tropical tropospheric trends increase with height. But the magnitude and the structure is highly data set dependent.

{image:'Fig27}

In summary, based on multiple independent analyses of measurements from radiosondes and satellite sensors it is virtually certain that globally the troposphere has warmed and the stratosphere has cooled since the mid-20th century. Despite unanimous agreement on the sign of the trends, substantial disagreement exists among available estimates as to the rate of temperature changes, particularly outside the NH extratropical troposphere, which has been well sampled by radiosondes. Hence there is only medium confidence in the rate of change and its vertical structure in the NH extratropical troposphere and low confidence elsewhere.
